export const CAMPAIGN_TEMPLATES = [
  {
    id: 'real_estate_hindi',
    name: 'Real Estate — Hindi',
    industry: 'Real Estate',
    language: 'hi',
    tts_provider: 'sarvam',
    tts_voice_id: 'amit',
    description: 'Hindi outbound calls for real estate lead qualification and site visit booking.',
    agent_persona: `You are a friendly real estate sales agent. You speak casual Hinglish. Your goal is to qualify the lead's interest and book a site visit. Be brief — 1 sentence max. Ask about their budget range and preferred location, then push for a visit.`,
    call_flow_instructions: `1. Greet and confirm they enquired about property\n2. Ask: "Aapko kis area mein property chahiye?"\n3. Ask: "Budget kitna hai roughly?"\n4. Push for site visit: "Ek baar site dekh lijiye, kab free hain?"\n5. Confirm date/time and end call`,
  },
  {
    id: 'real_estate_bengali',
    name: 'Real Estate — Bengali',
    industry: 'Real Estate',
    language: 'bn',
    tts_provider: 'sarvam',
    tts_voice_id: 'amit',
    description: 'Bengali outbound calls for real estate lead qualification and site visit booking.',
    agent_persona: `You are a friendly real estate sales agent. You speak casual Bengali with English mix. Your goal is to qualify the lead and book a site visit. Be brief — 1 sentence max.`,
    call_flow_instructions: `1. Greet and confirm enquiry\n2. Ask: "Apni kon area-te property khujchhen?"\n3. Ask: "Budget koto?"\n4. Push: "Ekbar site ta dekhun, kokhon free achen?"\n5. Confirm and end`,
  },
  {
    id: 'real_estate_marathi',
    name: 'Real Estate — Marathi',
    industry: 'Real Estate',
    language: 'mr',
    tts_provider: 'sarvam',
    tts_voice_id: 'kabir',
    description: 'Marathi outbound calls for real estate lead qualification.',
    agent_persona: `You are a friendly real estate sales agent. You speak casual Marathi with English mix. Goal: qualify lead and book site visit. 1 sentence max.`,
    call_flow_instructions: `1. Greet and confirm enquiry\n2. Ask: "Tumhala kuthla area pahije?"\n3. Ask: "Budget kiti ahe?"\n4. Push: "Ekda site bagha, kadhi free ahat?"\n5. Confirm and end`,
  },
  {
    id: 'edtech_hindi',
    name: 'Ed-Tech — Hindi',
    industry: 'Education',
    language: 'hi',
    tts_provider: 'sarvam',
    tts_voice_id: 'priya',
    description: 'Hindi calls for educational course enrollment and demo booking.',
    agent_persona: `You are a friendly education counselor. You speak casual Hinglish. Your goal is to understand the student's interest and book a free demo class. Be warm and encouraging.`,
    call_flow_instructions: `1. Greet and confirm course interest\n2. Ask: "Kaunsa course mein interest hai?"\n3. Brief pitch (1 line about the course)\n4. Push: "Ek free demo class attend kariye, kab free hain?"\n5. Confirm and end`,
  },
  {
    id: 'insurance_hindi',
    name: 'Insurance — Hindi',
    industry: 'Insurance',
    language: 'hi',
    tts_provider: 'sarvam',
    tts_voice_id: 'kabir',
    description: 'Hindi calls for insurance policy lead qualification.',
    agent_persona: `You are an insurance advisor. You speak casual Hinglish. Your goal is to understand coverage needs and book a consultation with a senior advisor. Don't quote prices — defer to the expert.`,
    call_flow_instructions: `1. Greet and confirm insurance enquiry\n2. Ask: "Health insurance ya life insurance?"\n3. Ask: "Family mein kitne members hain?"\n4. Push: "Humare advisor best plan suggest karenge, kab free hain?"\n5. Confirm and end`,
  },
  {
    id: 'fintech_hindi',
    name: 'Fintech / Loans — Hindi',
    industry: 'Fintech',
    language: 'hi',
    tts_provider: 'sarvam',
    tts_voice_id: 'rohan',
    description: 'Hindi calls for loan/fintech lead qualification.',
    agent_persona: `You are a friendly loan advisor. You speak casual Hinglish. Goal: understand loan requirement and book a callback from the processing team. Never promise approval or specific rates.`,
    call_flow_instructions: `1. Greet and confirm loan enquiry\n2. Ask: "Personal loan ya business loan?"\n3. Ask: "Roughly kitna amount chahiye?"\n4. Push: "Processing team call karegi details ke saath, kab free hain?"\n5. Confirm and end`,
  },
];

export const INDUSTRY_COLORS = {
  'Real Estate': { bg: 'rgba(234,179,8,0.15)', color: '#facc15' },
  'Education': { bg: 'rgba(96,165,250,0.15)', color: '#60a5fa' },
  'Insurance': { bg: 'rgba(34,197,94,0.15)', color: '#22c55e' },
  'Fintech': { bg: 'rgba(168,85,247,0.15)', color: '#a855f7' },
};

export const LANGUAGE_LABELS = {
  hi: 'Hindi',
  bn: 'Bengali',
  mr: 'Marathi',
  en: 'English',
  ta: 'Tamil',
  te: 'Telugu',
};
