# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from callified.v1 import audio_pipeline_pb2 as callified_dot_v1_dot_audio__pipeline__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in callified/v1/audio_pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CallLogicServiceStub(object):
    """Python implements this server. Go calls it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeCall = channel.unary_unary(
                '/callified.v1.CallLogicService/InitializeCall',
                request_serializer=callified_dot_v1_dot_audio__pipeline__pb2.InitCallRequest.SerializeToString,
                response_deserializer=callified_dot_v1_dot_audio__pipeline__pb2.InitCallResponse.FromString,
                _registered_method=True)
        self.ProcessTranscript = channel.unary_stream(
                '/callified.v1.CallLogicService/ProcessTranscript',
                request_serializer=callified_dot_v1_dot_audio__pipeline__pb2.TranscriptRequest.SerializeToString,
                response_deserializer=callified_dot_v1_dot_audio__pipeline__pb2.SentenceChunk.FromString,
                _registered_method=True)
        self.FinalizeCall = channel.unary_unary(
                '/callified.v1.CallLogicService/FinalizeCall',
                request_serializer=callified_dot_v1_dot_audio__pipeline__pb2.FinalizeCallRequest.SerializeToString,
                response_deserializer=callified_dot_v1_dot_audio__pipeline__pb2.FinalizeCallResponse.FromString,
                _registered_method=True)
        self.RetrieveContext = channel.unary_unary(
                '/callified.v1.CallLogicService/RetrieveContext',
                request_serializer=callified_dot_v1_dot_audio__pipeline__pb2.RAGRequest.SerializeToString,
                response_deserializer=callified_dot_v1_dot_audio__pipeline__pb2.RAGResponse.FromString,
                _registered_method=True)


class CallLogicServiceServicer(object):
    """Python implements this server. Go calls it.
    """

    def InitializeCall(self, request, context):
        """On WebSocket connect: returns system prompt, greeting, voice config
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessTranscript(self, request, context):
        """On each user transcript: streams LLM response as sentence chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeCall(self, request, context):
        """On call end: triggers recording save, transcript store, background analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveContext(self, request, context):
        """RAG context retrieval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallLogicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeCall': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeCall,
                    request_deserializer=callified_dot_v1_dot_audio__pipeline__pb2.InitCallRequest.FromString,
                    response_serializer=callified_dot_v1_dot_audio__pipeline__pb2.InitCallResponse.SerializeToString,
            ),
            'ProcessTranscript': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessTranscript,
                    request_deserializer=callified_dot_v1_dot_audio__pipeline__pb2.TranscriptRequest.FromString,
                    response_serializer=callified_dot_v1_dot_audio__pipeline__pb2.SentenceChunk.SerializeToString,
            ),
            'FinalizeCall': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeCall,
                    request_deserializer=callified_dot_v1_dot_audio__pipeline__pb2.FinalizeCallRequest.FromString,
                    response_serializer=callified_dot_v1_dot_audio__pipeline__pb2.FinalizeCallResponse.SerializeToString,
            ),
            'RetrieveContext': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveContext,
                    request_deserializer=callified_dot_v1_dot_audio__pipeline__pb2.RAGRequest.FromString,
                    response_serializer=callified_dot_v1_dot_audio__pipeline__pb2.RAGResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'callified.v1.CallLogicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('callified.v1.CallLogicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CallLogicService(object):
    """Python implements this server. Go calls it.
    """

    @staticmethod
    def InitializeCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callified.v1.CallLogicService/InitializeCall',
            callified_dot_v1_dot_audio__pipeline__pb2.InitCallRequest.SerializeToString,
            callified_dot_v1_dot_audio__pipeline__pb2.InitCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/callified.v1.CallLogicService/ProcessTranscript',
            callified_dot_v1_dot_audio__pipeline__pb2.TranscriptRequest.SerializeToString,
            callified_dot_v1_dot_audio__pipeline__pb2.SentenceChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callified.v1.CallLogicService/FinalizeCall',
            callified_dot_v1_dot_audio__pipeline__pb2.FinalizeCallRequest.SerializeToString,
            callified_dot_v1_dot_audio__pipeline__pb2.FinalizeCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callified.v1.CallLogicService/RetrieveContext',
            callified_dot_v1_dot_audio__pipeline__pb2.RAGRequest.SerializeToString,
            callified_dot_v1_dot_audio__pipeline__pb2.RAGResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
