#!/usr/bin/env bash
# set-ramp.sh — Change the percentage of /media-stream traffic routed to the Go audio service.
#
# Usage:
#   sudo ./scripts/set-ramp.sh <percentage>
#
# Supported values: 0, 10, 25, 50, 100
#   0   → 100% Python (instant rollback)
#   10  → 10% Go, 90% Python  (initial shadow mode)
#   25  → 25% Go, 75% Python
#   50  → 50% Go, 50% Python
#   100 → 100% Go             (full switchover)
#
# The script updates nginx/go_ramp.conf then reloads Nginx — no downtime.

set -euo pipefail

RAMP="${1:-}"
RAMP_FILE="/etc/nginx/conf.d/go_ramp.conf"

# ── Validate argument ─────────────────────────────────────────────────────────
case "$RAMP" in
    0|10|25|50|100) ;;
    *)
        echo "ERROR: Invalid ramp percentage: '$RAMP'"
        echo "Usage: $0 0|10|25|50|100"
        exit 1
        ;;
esac

PYTHON_PCT=$((100 - RAMP))

# ── Write the new ramp config ─────────────────────────────────────────────────
cat > "$RAMP_FILE" << EOF
# go_ramp.conf — auto-generated by scripts/set-ramp.sh
# Go: ${RAMP}%   Python: ${PYTHON_PCT}%
# Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

split_clients "\${remote_addr}" \$audio_upstream {
$([ "$RAMP" -gt 0 ] && echo "    ${RAMP}%   go_audio;")
    *     python_api;
}
EOF

echo "Written: $RAMP_FILE"

# ── Test and reload Nginx ─────────────────────────────────────────────────────
echo "Testing Nginx config..."
nginx -t

echo "Reloading Nginx..."
systemctl reload nginx

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "Traffic split updated:"
echo "  Go audio service  (localhost:8001): ${RAMP}%"
echo "  Python legacy     (localhost:8000): ${PYTHON_PCT}%"
echo ""

if [ "$RAMP" -eq 100 ]; then
    echo "*** FULL SWITCHOVER — Python /media-stream is no longer receiving new calls ***"
    echo "    Python REST API remains active at /api/*"
elif [ "$RAMP" -eq 0 ]; then
    echo "*** ROLLBACK — All traffic returned to Python ***"
fi
