// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: callified/v1/audio_pipeline.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadName      string                 `protobuf:"bytes,1,opt,name=lead_name,json=leadName,proto3" json:"lead_name,omitempty"`
	LeadPhone     string                 `protobuf:"bytes,2,opt,name=lead_phone,json=leadPhone,proto3" json:"lead_phone,omitempty"`
	Interest      string                 `protobuf:"bytes,3,opt,name=interest,proto3" json:"interest,omitempty"`
	LeadId        int64                  `protobuf:"varint,4,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	CampaignId    int64                  `protobuf:"varint,5,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	OrgId         int64                  `protobuf:"varint,6,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Language      string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"` // "hi", "mr", "en", "ta", "te", "bn", "gu", "kn", "ml", "pa"
	StreamSid     string                 `protobuf:"bytes,8,opt,name=stream_sid,json=streamSid,proto3" json:"stream_sid,omitempty"`
	CallSid       string                 `protobuf:"bytes,9,opt,name=call_sid,json=callSid,proto3" json:"call_sid,omitempty"` // Exotel/Twilio callSid — used for recording fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitCallRequest) Reset() {
	*x = InitCallRequest{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCallRequest) ProtoMessage() {}

func (x *InitCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCallRequest.ProtoReflect.Descriptor instead.
func (*InitCallRequest) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *InitCallRequest) GetLeadName() string {
	if x != nil {
		return x.LeadName
	}
	return ""
}

func (x *InitCallRequest) GetLeadPhone() string {
	if x != nil {
		return x.LeadPhone
	}
	return ""
}

func (x *InitCallRequest) GetInterest() string {
	if x != nil {
		return x.Interest
	}
	return ""
}

func (x *InitCallRequest) GetLeadId() int64 {
	if x != nil {
		return x.LeadId
	}
	return 0
}

func (x *InitCallRequest) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *InitCallRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *InitCallRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *InitCallRequest) GetStreamSid() string {
	if x != nil {
		return x.StreamSid
	}
	return ""
}

func (x *InitCallRequest) GetCallSid() string {
	if x != nil {
		return x.CallSid
	}
	return ""
}

type InitCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt  string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	GreetingText  string                 `protobuf:"bytes,2,opt,name=greeting_text,json=greetingText,proto3" json:"greeting_text,omitempty"`
	TtsProvider   string                 `protobuf:"bytes,3,opt,name=tts_provider,json=ttsProvider,proto3" json:"tts_provider,omitempty"` // "sarvam" | "elevenlabs" | "smallest"
	TtsVoiceId    string                 `protobuf:"bytes,4,opt,name=tts_voice_id,json=ttsVoiceId,proto3" json:"tts_voice_id,omitempty"`
	TtsLanguage   string                 `protobuf:"bytes,5,opt,name=tts_language,json=ttsLanguage,proto3" json:"tts_language,omitempty"` // e.g. "hi-IN", "mr-IN"
	AgentName     string                 `protobuf:"bytes,6,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`       // e.g. "अर्जुन" or "प्रिया"
	Language      string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitCallResponse) Reset() {
	*x = InitCallResponse{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCallResponse) ProtoMessage() {}

func (x *InitCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCallResponse.ProtoReflect.Descriptor instead.
func (*InitCallResponse) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *InitCallResponse) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *InitCallResponse) GetGreetingText() string {
	if x != nil {
		return x.GreetingText
	}
	return ""
}

func (x *InitCallResponse) GetTtsProvider() string {
	if x != nil {
		return x.TtsProvider
	}
	return ""
}

func (x *InitCallResponse) GetTtsVoiceId() string {
	if x != nil {
		return x.TtsVoiceId
	}
	return ""
}

func (x *InitCallResponse) GetTtsLanguage() string {
	if x != nil {
		return x.TtsLanguage
	}
	return ""
}

func (x *InitCallResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *InitCallResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" | "model"
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	History       []*ChatMessage         `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptRequest) Reset() {
	*x = TranscriptRequest{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptRequest) ProtoMessage() {}

func (x *TranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptRequest.ProtoReflect.Descriptor instead.
func (*TranscriptRequest) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *TranscriptRequest) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *TranscriptRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *TranscriptRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *TranscriptRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscriptRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type SentenceChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsLast        bool                   `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	HasHangup     bool                   `protobuf:"varint,3,opt,name=has_hangup,json=hasHangup,proto3" json:"has_hangup,omitempty"` // LLM emitted [HANGUP] — Go should begin shutdown sequence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentenceChunk) Reset() {
	*x = SentenceChunk{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentenceChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentenceChunk) ProtoMessage() {}

func (x *SentenceChunk) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentenceChunk.ProtoReflect.Descriptor instead.
func (*SentenceChunk) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *SentenceChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SentenceChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *SentenceChunk) GetHasHangup() bool {
	if x != nil {
		return x.HasHangup
	}
	return false
}

type FinalizeCallRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StreamSid          string                 `protobuf:"bytes,1,opt,name=stream_sid,json=streamSid,proto3" json:"stream_sid,omitempty"`
	LeadId             int64                  `protobuf:"varint,2,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	CampaignId         int64                  `protobuf:"varint,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CallSid            string                 `protobuf:"bytes,4,opt,name=call_sid,json=callSid,proto3" json:"call_sid,omitempty"` // for Exotel recording fetch
	ChatHistory        []*ChatMessage         `protobuf:"bytes,5,rep,name=chat_history,json=chatHistory,proto3" json:"chat_history,omitempty"`
	CallDurationS      float32                `protobuf:"fixed32,6,opt,name=call_duration_s,json=callDurationS,proto3" json:"call_duration_s,omitempty"`
	StereoWav          []byte                 `protobuf:"bytes,7,opt,name=stereo_wav,json=stereoWav,proto3" json:"stereo_wav,omitempty"` // server-side recording (L=user R=AI), may be empty
	HasServerRecording bool                   `protobuf:"varint,8,opt,name=has_server_recording,json=hasServerRecording,proto3" json:"has_server_recording,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FinalizeCallRequest) Reset() {
	*x = FinalizeCallRequest{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeCallRequest) ProtoMessage() {}

func (x *FinalizeCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeCallRequest.ProtoReflect.Descriptor instead.
func (*FinalizeCallRequest) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *FinalizeCallRequest) GetStreamSid() string {
	if x != nil {
		return x.StreamSid
	}
	return ""
}

func (x *FinalizeCallRequest) GetLeadId() int64 {
	if x != nil {
		return x.LeadId
	}
	return 0
}

func (x *FinalizeCallRequest) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *FinalizeCallRequest) GetCallSid() string {
	if x != nil {
		return x.CallSid
	}
	return ""
}

func (x *FinalizeCallRequest) GetChatHistory() []*ChatMessage {
	if x != nil {
		return x.ChatHistory
	}
	return nil
}

func (x *FinalizeCallRequest) GetCallDurationS() float32 {
	if x != nil {
		return x.CallDurationS
	}
	return 0
}

func (x *FinalizeCallRequest) GetStereoWav() []byte {
	if x != nil {
		return x.StereoWav
	}
	return nil
}

func (x *FinalizeCallRequest) GetHasServerRecording() bool {
	if x != nil {
		return x.HasServerRecording
	}
	return false
}

type FinalizeCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordingUrl  string                 `protobuf:"bytes,1,opt,name=recording_url,json=recordingUrl,proto3" json:"recording_url,omitempty"` // /api/recordings/<filename> or ""
	TranscriptId  int64                  `protobuf:"varint,2,opt,name=transcript_id,json=transcriptId,proto3" json:"transcript_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeCallResponse) Reset() {
	*x = FinalizeCallResponse{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeCallResponse) ProtoMessage() {}

func (x *FinalizeCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeCallResponse.ProtoReflect.Descriptor instead.
func (*FinalizeCallResponse) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizeCallResponse) GetRecordingUrl() string {
	if x != nil {
		return x.RecordingUrl
	}
	return ""
}

func (x *FinalizeCallResponse) GetTranscriptId() int64 {
	if x != nil {
		return x.TranscriptId
	}
	return 0
}

type RAGRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	LeadId        int64                  `protobuf:"varint,2,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	OrgId         int64                  `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGRequest) Reset() {
	*x = RAGRequest{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGRequest) ProtoMessage() {}

func (x *RAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGRequest.ProtoReflect.Descriptor instead.
func (*RAGRequest) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *RAGRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RAGRequest) GetLeadId() int64 {
	if x != nil {
		return x.LeadId
	}
	return 0
}

func (x *RAGRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

type RAGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGResponse) Reset() {
	*x = RAGResponse{}
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGResponse) ProtoMessage() {}

func (x *RAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callified_v1_audio_pipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGResponse.ProtoReflect.Descriptor instead.
func (*RAGResponse) Descriptor() ([]byte, []int) {
	return file_callified_v1_audio_pipeline_proto_rawDescGZIP(), []int{8}
}

func (x *RAGResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

var File_callified_v1_audio_pipeline_proto protoreflect.FileDescriptor

const file_callified_v1_audio_pipeline_proto_rawDesc = "" +
	"\n" +
	"!callified/v1/audio_pipeline.proto\x12\fcallified.v1\"\x90\x02\n" +
	"\x0fInitCallRequest\x12\x1b\n" +
	"\tlead_name\x18\x01 \x01(\tR\bleadName\x12\x1d\n" +
	"\n" +
	"lead_phone\x18\x02 \x01(\tR\tleadPhone\x12\x1a\n" +
	"\binterest\x18\x03 \x01(\tR\binterest\x12\x17\n" +
	"\alead_id\x18\x04 \x01(\x03R\x06leadId\x12\x1f\n" +
	"\vcampaign_id\x18\x05 \x01(\x03R\n" +
	"campaignId\x12\x15\n" +
	"\x06org_id\x18\x06 \x01(\x03R\x05orgId\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"stream_sid\x18\b \x01(\tR\tstreamSid\x12\x19\n" +
	"\bcall_sid\x18\t \x01(\tR\acallSid\"\xff\x01\n" +
	"\x10InitCallResponse\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt\x12#\n" +
	"\rgreeting_text\x18\x02 \x01(\tR\fgreetingText\x12!\n" +
	"\ftts_provider\x18\x03 \x01(\tR\vttsProvider\x12 \n" +
	"\ftts_voice_id\x18\x04 \x01(\tR\n" +
	"ttsVoiceId\x12!\n" +
	"\ftts_language\x18\x05 \x01(\tR\vttsLanguage\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x06 \x01(\tR\tagentName\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\"5\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xc8\x01\n" +
	"\x11TranscriptRequest\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x123\n" +
	"\ahistory\x18\x03 \x03(\v2\x19.callified.v1.ChatMessageR\ahistory\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\"[\n" +
	"\rSentenceChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\x12\x1d\n" +
	"\n" +
	"has_hangup\x18\x03 \x01(\bR\thasHangup\"\xc0\x02\n" +
	"\x13FinalizeCallRequest\x12\x1d\n" +
	"\n" +
	"stream_sid\x18\x01 \x01(\tR\tstreamSid\x12\x17\n" +
	"\alead_id\x18\x02 \x01(\x03R\x06leadId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\x03R\n" +
	"campaignId\x12\x19\n" +
	"\bcall_sid\x18\x04 \x01(\tR\acallSid\x12<\n" +
	"\fchat_history\x18\x05 \x03(\v2\x19.callified.v1.ChatMessageR\vchatHistory\x12&\n" +
	"\x0fcall_duration_s\x18\x06 \x01(\x02R\rcallDurationS\x12\x1d\n" +
	"\n" +
	"stereo_wav\x18\a \x01(\fR\tstereoWav\x120\n" +
	"\x14has_server_recording\x18\b \x01(\bR\x12hasServerRecording\"`\n" +
	"\x14FinalizeCallResponse\x12#\n" +
	"\rrecording_url\x18\x01 \x01(\tR\frecordingUrl\x12#\n" +
	"\rtranscript_id\x18\x02 \x01(\x03R\ftranscriptId\"R\n" +
	"\n" +
	"RAGRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\alead_id\x18\x02 \x01(\x03R\x06leadId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\x03R\x05orgId\"'\n" +
	"\vRAGResponse\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext2\xd7\x02\n" +
	"\x10CallLogicService\x12O\n" +
	"\x0eInitializeCall\x12\x1d.callified.v1.InitCallRequest\x1a\x1e.callified.v1.InitCallResponse\x12S\n" +
	"\x11ProcessTranscript\x12\x1f.callified.v1.TranscriptRequest\x1a\x1b.callified.v1.SentenceChunk0\x01\x12U\n" +
	"\fFinalizeCall\x12!.callified.v1.FinalizeCallRequest\x1a\".callified.v1.FinalizeCallResponse\x12F\n" +
	"\x0fRetrieveContext\x12\x18.callified.v1.RAGRequest\x1a\x19.callified.v1.RAGResponseB3Z1github.com/globussoft/callified-backend/internal/pbb\x06proto3"

var (
	file_callified_v1_audio_pipeline_proto_rawDescOnce sync.Once
	file_callified_v1_audio_pipeline_proto_rawDescData []byte
)

func file_callified_v1_audio_pipeline_proto_rawDescGZIP() []byte {
	file_callified_v1_audio_pipeline_proto_rawDescOnce.Do(func() {
		file_callified_v1_audio_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_callified_v1_audio_pipeline_proto_rawDesc), len(file_callified_v1_audio_pipeline_proto_rawDesc)))
	})
	return file_callified_v1_audio_pipeline_proto_rawDescData
}

var file_callified_v1_audio_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_callified_v1_audio_pipeline_proto_goTypes = []any{
	(*InitCallRequest)(nil),      // 0: callified.v1.InitCallRequest
	(*InitCallResponse)(nil),     // 1: callified.v1.InitCallResponse
	(*ChatMessage)(nil),          // 2: callified.v1.ChatMessage
	(*TranscriptRequest)(nil),    // 3: callified.v1.TranscriptRequest
	(*SentenceChunk)(nil),        // 4: callified.v1.SentenceChunk
	(*FinalizeCallRequest)(nil),  // 5: callified.v1.FinalizeCallRequest
	(*FinalizeCallResponse)(nil), // 6: callified.v1.FinalizeCallResponse
	(*RAGRequest)(nil),           // 7: callified.v1.RAGRequest
	(*RAGResponse)(nil),          // 8: callified.v1.RAGResponse
}
var file_callified_v1_audio_pipeline_proto_depIdxs = []int32{
	2, // 0: callified.v1.TranscriptRequest.history:type_name -> callified.v1.ChatMessage
	2, // 1: callified.v1.FinalizeCallRequest.chat_history:type_name -> callified.v1.ChatMessage
	0, // 2: callified.v1.CallLogicService.InitializeCall:input_type -> callified.v1.InitCallRequest
	3, // 3: callified.v1.CallLogicService.ProcessTranscript:input_type -> callified.v1.TranscriptRequest
	5, // 4: callified.v1.CallLogicService.FinalizeCall:input_type -> callified.v1.FinalizeCallRequest
	7, // 5: callified.v1.CallLogicService.RetrieveContext:input_type -> callified.v1.RAGRequest
	1, // 6: callified.v1.CallLogicService.InitializeCall:output_type -> callified.v1.InitCallResponse
	4, // 7: callified.v1.CallLogicService.ProcessTranscript:output_type -> callified.v1.SentenceChunk
	6, // 8: callified.v1.CallLogicService.FinalizeCall:output_type -> callified.v1.FinalizeCallResponse
	8, // 9: callified.v1.CallLogicService.RetrieveContext:output_type -> callified.v1.RAGResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_callified_v1_audio_pipeline_proto_init() }
func file_callified_v1_audio_pipeline_proto_init() {
	if File_callified_v1_audio_pipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callified_v1_audio_pipeline_proto_rawDesc), len(file_callified_v1_audio_pipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_callified_v1_audio_pipeline_proto_goTypes,
		DependencyIndexes: file_callified_v1_audio_pipeline_proto_depIdxs,
		MessageInfos:      file_callified_v1_audio_pipeline_proto_msgTypes,
	}.Build()
	File_callified_v1_audio_pipeline_proto = out.File
	file_callified_v1_audio_pipeline_proto_goTypes = nil
	file_callified_v1_audio_pipeline_proto_depIdxs = nil
}
