// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: callified/v1/audio_pipeline.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallLogicService_InitializeCall_FullMethodName    = "/callified.v1.CallLogicService/InitializeCall"
	CallLogicService_ProcessTranscript_FullMethodName = "/callified.v1.CallLogicService/ProcessTranscript"
	CallLogicService_FinalizeCall_FullMethodName      = "/callified.v1.CallLogicService/FinalizeCall"
	CallLogicService_RetrieveContext_FullMethodName   = "/callified.v1.CallLogicService/RetrieveContext"
)

// CallLogicServiceClient is the client API for CallLogicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Python implements this server. Go calls it.
type CallLogicServiceClient interface {
	// On WebSocket connect: returns system prompt, greeting, voice config
	InitializeCall(ctx context.Context, in *InitCallRequest, opts ...grpc.CallOption) (*InitCallResponse, error)
	// On each user transcript: streams LLM response as sentence chunks
	ProcessTranscript(ctx context.Context, in *TranscriptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SentenceChunk], error)
	// On call end: triggers recording save, transcript store, background analysis
	FinalizeCall(ctx context.Context, in *FinalizeCallRequest, opts ...grpc.CallOption) (*FinalizeCallResponse, error)
	// RAG context retrieval
	RetrieveContext(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (*RAGResponse, error)
}

type callLogicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallLogicServiceClient(cc grpc.ClientConnInterface) CallLogicServiceClient {
	return &callLogicServiceClient{cc}
}

func (c *callLogicServiceClient) InitializeCall(ctx context.Context, in *InitCallRequest, opts ...grpc.CallOption) (*InitCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitCallResponse)
	err := c.cc.Invoke(ctx, CallLogicService_InitializeCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callLogicServiceClient) ProcessTranscript(ctx context.Context, in *TranscriptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SentenceChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CallLogicService_ServiceDesc.Streams[0], CallLogicService_ProcessTranscript_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranscriptRequest, SentenceChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallLogicService_ProcessTranscriptClient = grpc.ServerStreamingClient[SentenceChunk]

func (c *callLogicServiceClient) FinalizeCall(ctx context.Context, in *FinalizeCallRequest, opts ...grpc.CallOption) (*FinalizeCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeCallResponse)
	err := c.cc.Invoke(ctx, CallLogicService_FinalizeCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callLogicServiceClient) RetrieveContext(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (*RAGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGResponse)
	err := c.cc.Invoke(ctx, CallLogicService_RetrieveContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallLogicServiceServer is the server API for CallLogicService service.
// All implementations must embed UnimplementedCallLogicServiceServer
// for forward compatibility.
//
// Python implements this server. Go calls it.
type CallLogicServiceServer interface {
	// On WebSocket connect: returns system prompt, greeting, voice config
	InitializeCall(context.Context, *InitCallRequest) (*InitCallResponse, error)
	// On each user transcript: streams LLM response as sentence chunks
	ProcessTranscript(*TranscriptRequest, grpc.ServerStreamingServer[SentenceChunk]) error
	// On call end: triggers recording save, transcript store, background analysis
	FinalizeCall(context.Context, *FinalizeCallRequest) (*FinalizeCallResponse, error)
	// RAG context retrieval
	RetrieveContext(context.Context, *RAGRequest) (*RAGResponse, error)
	mustEmbedUnimplementedCallLogicServiceServer()
}

// UnimplementedCallLogicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallLogicServiceServer struct{}

func (UnimplementedCallLogicServiceServer) InitializeCall(context.Context, *InitCallRequest) (*InitCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeCall not implemented")
}
func (UnimplementedCallLogicServiceServer) ProcessTranscript(*TranscriptRequest, grpc.ServerStreamingServer[SentenceChunk]) error {
	return status.Error(codes.Unimplemented, "method ProcessTranscript not implemented")
}
func (UnimplementedCallLogicServiceServer) FinalizeCall(context.Context, *FinalizeCallRequest) (*FinalizeCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeCall not implemented")
}
func (UnimplementedCallLogicServiceServer) RetrieveContext(context.Context, *RAGRequest) (*RAGResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveContext not implemented")
}
func (UnimplementedCallLogicServiceServer) mustEmbedUnimplementedCallLogicServiceServer() {}
func (UnimplementedCallLogicServiceServer) testEmbeddedByValue()                          {}

// UnsafeCallLogicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallLogicServiceServer will
// result in compilation errors.
type UnsafeCallLogicServiceServer interface {
	mustEmbedUnimplementedCallLogicServiceServer()
}

func RegisterCallLogicServiceServer(s grpc.ServiceRegistrar, srv CallLogicServiceServer) {
	// If the following call panics, it indicates UnimplementedCallLogicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallLogicService_ServiceDesc, srv)
}

func _CallLogicService_InitializeCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallLogicServiceServer).InitializeCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallLogicService_InitializeCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallLogicServiceServer).InitializeCall(ctx, req.(*InitCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallLogicService_ProcessTranscript_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranscriptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CallLogicServiceServer).ProcessTranscript(m, &grpc.GenericServerStream[TranscriptRequest, SentenceChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallLogicService_ProcessTranscriptServer = grpc.ServerStreamingServer[SentenceChunk]

func _CallLogicService_FinalizeCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallLogicServiceServer).FinalizeCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallLogicService_FinalizeCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallLogicServiceServer).FinalizeCall(ctx, req.(*FinalizeCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallLogicService_RetrieveContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallLogicServiceServer).RetrieveContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallLogicService_RetrieveContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallLogicServiceServer).RetrieveContext(ctx, req.(*RAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallLogicService_ServiceDesc is the grpc.ServiceDesc for CallLogicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallLogicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "callified.v1.CallLogicService",
	HandlerType: (*CallLogicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeCall",
			Handler:    _CallLogicService_InitializeCall_Handler,
		},
		{
			MethodName: "FinalizeCall",
			Handler:    _CallLogicService_FinalizeCall_Handler,
		},
		{
			MethodName: "RetrieveContext",
			Handler:    _CallLogicService_RetrieveContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessTranscript",
			Handler:       _CallLogicService_ProcessTranscript_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "callified/v1/audio_pipeline.proto",
}
